---
ping_localhost:
  every: 1m
  class: PingJob
  args:
  - '1'
job_for_item_1_on_host_1:
  every:
  - 1m
  class: ScheduleItemJob
  args:
  - '1'
  - '1'
job_for_item_2_on_host_1:
  every:
  - 10m
  class: ScheduleItemJob
  args:
  - '1'
  - '2'
