---
ping_localhost:
  every: 1m
  class: PingJob
  args:
  - '1'
ping_pi.remote:
  every:
  - 1m
  class: PingJob
  args:
  - 3
ping_centos.solomon-andrei.com:
  every:
  - 1m
  class: PingJob
  args:
  - 4
ping_ubuntu.solomon-andrei.com:
  every:
  - 1m
  class: PingJob
  args:
  - 5
