---
ping_localhost:
  every: 1m
  class: PingJob
  args:
  - '1'
check_active_alerts:
  every: 1m
  class: CheckActiveAlertsJob
ping_pi.remote:
  every:
  - 1m
  class: PingJob
  args:
  - 3
ping_centos.solomon-andrei.com:
  every:
  - 1m
  class: PingJob
  args:
  - 4
ping_ubuntu.solomon-andrei.com:
  every:
  - 1m
  class: PingJob
  args:
  - 5
autopatch_overwatch.localhost:
  every:
  - 1d
  class: AutopatchJob
  args:
  - 1
job_for_item_15_on_host_4:
  every:
  - 1m
  class: ScheduleItemJob
  args:
  - '4'
  - '15'
job_for_item_15_on_host_5:
  every:
  - 1m
  class: ScheduleItemJob
  args:
  - '5'
  - '15'
